"""Initial StudyTable schema

Revision ID: 192e6c6d0922
Revises: 
Create Date: 2026-10-05 09:05:19.219696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192e6c6d0922'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('school', sa.String(length=160), nullable=True),
    sa.Column('program', sa.String(length=160), nullable=True),
    sa.Column('year_of_study', sa.Integer(), nullable=True),
    sa.Column('interests', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_email', ['email'], unique=False)

    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day')
    )
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.create_index('ix_ai_usage_user_day', ['user_id', 'day'], unique=False)

    op.create_table('daily_insight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day')
    )
    with op.batch_alter_table('daily_insight', schema=None) as batch_op:
        batch_op.create_index('ix_daily_insight_user_day', ['user_id', 'day'], unique=False)

    op.create_table('year',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'number')
    )
    with op.batch_alter_table('year', schema=None) as batch_op:
        batch_op.create_index('ix_year_user_number', ['user_id', 'number'], unique=False)

    op.create_table('semester',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('timetable_filename', sa.String(length=255), nullable=True),
    sa.Column('timetable_stored_name', sa.String(length=255), nullable=True),
    sa.Column('exam_timetable_filename', sa.String(length=255), nullable=True),
    sa.Column('exam_timetable_stored_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['year_id'], ['year.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_id', 'number')
    )
    with op.batch_alter_table('semester', schema=None) as batch_op:
        batch_op.create_index('ix_semester_year_number', ['year_id', 'number'], unique=False)

    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index('ix_course_user_name', ['user_id', 'name'], unique=False)
        batch_op.create_index('ix_course_user_semester', ['user_id', 'semester_id'], unique=False)

    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('course_name', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.create_index('ix_assessment_date', ['date'], unique=False)
        batch_op.create_index('ix_assessment_semester_date', ['semester_id', 'date'], unique=False)

    op.create_table('cat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.create_index('ix_cat_course_created', ['course_id', 'created_at'], unique=False)

    op.create_table('class_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('course_name', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_session', schema=None) as batch_op:
        batch_op.create_index('ix_class_session_semester_weekday', ['semester_id', 'weekday'], unique=False)
        batch_op.create_index('ix_class_session_weekday', ['weekday'], unique=False)

    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index('ix_document_course_id', ['course_id'], unique=False)

    op.create_table('cat_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('chosen_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['cat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_question', schema=None) as batch_op:
        batch_op.create_index('ix_cat_question_cat_position', ['cat_id', 'position'], unique=False)

    op.create_table('flashcard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('box', sa.Integer(), nullable=False),
    sa.Column('times_right', sa.Integer(), nullable=False),
    sa.Column('times_wrong', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flashcard', schema=None) as batch_op:
        batch_op.create_index('ix_flashcard_document_due', ['document_id', 'due_at'], unique=False)
        batch_op.create_index('ix_flashcard_document_page', ['document_id', 'page_number'], unique=False)
        batch_op.create_index('ix_flashcard_due_at', ['due_at'], unique=False)

    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('seconds_spent', sa.Integer(), nullable=False),
    sa.Column('studied', sa.Boolean(), nullable=False),
    sa.Column('cards_made', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number')
    )
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.create_index('ix_page_document_cards_made', ['document_id', 'cards_made'], unique=False)
        batch_op.create_index('ix_page_document_page', ['document_id', 'page_number'], unique=False)
        batch_op.create_index('ix_page_document_studied', ['document_id', 'studied'], unique=False)
        batch_op.create_index('ix_page_study_cards', ['document_id', 'studied', 'cards_made'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_index('ix_page_study_cards')
        batch_op.drop_index('ix_page_document_studied')
        batch_op.drop_index('ix_page_document_page')
        batch_op.drop_index('ix_page_document_cards_made')

    op.drop_table('page')
    with op.batch_alter_table('flashcard', schema=None) as batch_op:
        batch_op.drop_index('ix_flashcard_due_at')
        batch_op.drop_index('ix_flashcard_document_page')
        batch_op.drop_index('ix_flashcard_document_due')

    op.drop_table('flashcard')
    with op.batch_alter_table('cat_question', schema=None) as batch_op:
        batch_op.drop_index('ix_cat_question_cat_position')

    op.drop_table('cat_question')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index('ix_document_course_id')

    op.drop_table('document')
    with op.batch_alter_table('class_session', schema=None) as batch_op:
        batch_op.drop_index('ix_class_session_weekday')
        batch_op.drop_index('ix_class_session_semester_weekday')

    op.drop_table('class_session')
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.drop_index('ix_cat_course_created')

    op.drop_table('cat')
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.drop_index('ix_assessment_semester_date')
        batch_op.drop_index('ix_assessment_date')

    op.drop_table('assessment')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index('ix_course_user_semester')
        batch_op.drop_index('ix_course_user_name')

    op.drop_table('course')
    with op.batch_alter_table('semester', schema=None) as batch_op:
        batch_op.drop_index('ix_semester_year_number')

    op.drop_table('semester')
    with op.batch_alter_table('year', schema=None) as batch_op:
        batch_op.drop_index('ix_year_user_number')

    op.drop_table('year')
    with op.batch_alter_table('daily_insight', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_insight_user_day')

    op.drop_table('daily_insight')
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_usage_user_day')

    op.drop_table('ai_usage')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')

    op.drop_table('user')
    # ### end Alembic commands ###
